<?php declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20181221144952 extends AbstractMigration
{
    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE CONTAINER_MODEL CHANGE NAME NAME VARCHAR(255) NOT NULL, CHANGE LENGTH LENGTH INT NOT NULL, CHANGE WIDTH WIDTH INT NOT NULL, CHANGE HEIGHT HEIGHT INT NOT NULL');
        $this->addSql('ALTER TABLE CONTAINERSHIP CHANGE NAME NAME VARCHAR(255) NOT NULL, CHANGE CAPTAIN_NAME CAPTAIN_NAME VARCHAR(255) NOT NULL, CHANGE CONTAINER_LIMIT Container_LIMIT INT NOT NULL');
        $this->addSql('ALTER TABLE PRODUCT CHANGE NAME NAME VARCHAR(255) NOT NULL, CHANGE LENGTH LENGTH INT NOT NULL, CHANGE WIDTH WIDTH INT NOT NULL, CHANGE HEIGHT HEIGHT INT NOT NULL');
        $this->addSql('ALTER TABLE CONTAINER DROP FOREIGN KEY CONTAINER_CONTAINERSHIP_ID_fk');
        $this->addSql('ALTER TABLE CONTAINER DROP FOREIGN KEY CONTAINER_CONTAINER_MODEL_ID_fk');
        $this->addSql('DROP INDEX CONTAINER_ID_uindex ON CONTAINER');
        $this->addSql('DROP INDEX CONTAINER_CONTAINERSHIP_ID_fk ON CONTAINER');
        $this->addSql('DROP INDEX CONTAINER_CONTAINER_MODEL_ID_fk ON CONTAINER');
        $this->addSql('ALTER TABLE CONTAINER CHANGE COLOR COLOR VARCHAR(255) NOT NULL, CHANGE CONTAINER_MODEL_ID CONTAINER_MODEL_ID INT NOT NULL, CHANGE CONTAINERSHIP_ID CONTAINERSHIP_ID INT NOT NULL');
        $this->addSql('ALTER TABLE CONTAINER_PRODUCT DROP FOREIGN KEY CONTAINER_PRODUCT_CONTAINER_ID_fk');
        $this->addSql('ALTER TABLE CONTAINER_PRODUCT DROP FOREIGN KEY CONTAINER_PRODUCT_PRODUCT_ID_fk');
        $this->addSql('DROP INDEX CONTAINER_PRODUCT_CONTAINER_ID_fk ON CONTAINER_PRODUCT');
        $this->addSql('DROP INDEX CONTAINER_PRODUCT_PRODUCT_ID_fk ON CONTAINER_PRODUCT');
        $this->addSql('ALTER TABLE CONTAINER_PRODUCT CHANGE CONTAINER_ID CONTAINER_ID INT NOT NULL, CHANGE PRODUCT_ID PRODUCT_ID INT NOT NULL, CHANGE QUANTITY QUANTITY INT NOT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE container CHANGE COLOR COLOR VARCHAR(20) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE CONTAINER_MODEL_ID CONTAINER_MODEL_ID INT DEFAULT NULL, CHANGE CONTAINERSHIP_ID CONTAINERSHIP_ID INT DEFAULT NULL');
        $this->addSql('ALTER TABLE container ADD CONSTRAINT CONTAINER_CONTAINERSHIP_ID_fk FOREIGN KEY (CONTAINERSHIP_ID) REFERENCES CONTAINERSHIP (ID)');
        $this->addSql('ALTER TABLE container ADD CONSTRAINT CONTAINER_CONTAINER_MODEL_ID_fk FOREIGN KEY (CONTAINER_MODEL_ID) REFERENCES CONTAINER_MODEL (ID)');
        $this->addSql('CREATE UNIQUE INDEX CONTAINER_ID_uindex ON container (ID)');
        $this->addSql('CREATE INDEX CONTAINER_CONTAINERSHIP_ID_fk ON container (CONTAINERSHIP_ID)');
        $this->addSql('CREATE INDEX CONTAINER_CONTAINER_MODEL_ID_fk ON container (CONTAINER_MODEL_ID)');
        $this->addSql('ALTER TABLE containership CHANGE NAME NAME VARCHAR(255) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE CAPTAIN_NAME CAPTAIN_NAME VARCHAR(255) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE Container_LIMIT CONTAINER_LIMIT INT DEFAULT NULL');
        $this->addSql('ALTER TABLE container_model CHANGE NAME NAME VARCHAR(255) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE LENGTH LENGTH INT DEFAULT NULL, CHANGE WIDTH WIDTH INT DEFAULT NULL, CHANGE HEIGHT HEIGHT INT DEFAULT NULL');
        $this->addSql('ALTER TABLE container_product CHANGE CONTAINER_ID CONTAINER_ID INT DEFAULT NULL, CHANGE PRODUCT_ID PRODUCT_ID INT DEFAULT NULL, CHANGE QUANTITY QUANTITY INT DEFAULT NULL');
        $this->addSql('ALTER TABLE container_product ADD CONSTRAINT CONTAINER_PRODUCT_CONTAINER_ID_fk FOREIGN KEY (CONTAINER_ID) REFERENCES CONTAINER (ID)');
        $this->addSql('ALTER TABLE container_product ADD CONSTRAINT CONTAINER_PRODUCT_PRODUCT_ID_fk FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)');
        $this->addSql('CREATE INDEX CONTAINER_PRODUCT_CONTAINER_ID_fk ON container_product (CONTAINER_ID)');
        $this->addSql('CREATE INDEX CONTAINER_PRODUCT_PRODUCT_ID_fk ON container_product (PRODUCT_ID)');
        $this->addSql('ALTER TABLE product CHANGE NAME NAME VARCHAR(255) DEFAULT NULL COLLATE latin1_swedish_ci, CHANGE LENGTH LENGTH INT DEFAULT NULL, CHANGE WIDTH WIDTH INT DEFAULT NULL, CHANGE HEIGHT HEIGHT INT DEFAULT NULL');
    }
}
